### PR TITLE
Dustoff

### PR DESCRIPTION
**Pull request by mcbloch**
Todo: 

- [x] check timezone -> do we need the following?
```
config.time_zone = 'Brussels'
```
- [x] check actionmailer in production -> do we need the following?
```
-  config.action_mailer.delivery_method = :sendmail
-  config.action_mailer.default_url_options = { host: 'event.fkgent.be' }
```
- [x] add ckeditor back (or another WYSIWYG editor) -> ckeditor bad, froala misleading, tinymce is my new best friend
- [x] fix bootstrap datetimepickers
- [x] check email generation in production (focus on barcode)
- [x] fix typeahead styling
- [x] upgrade to rails 6
- [x] upgrade to latest ruby
- [x]  check CAS login
- [x] make all tests pass

### CODE REVIEW

**Comment by redfast00** [comment]
Is this a development or production Dockerfile?

**Comment by mcbloch** [comment]
At the moment only development. It's there atm to ensure it works in an isolated environment and not only on my pc.

**Comment by redfast00** [comment]
Using the `letter_opener` gem, you can now preview mails in development: they will be opened in the browser

**Comment by redfast00** [comment]
I was also going to make barcodes non-transparent, but it seems that switching to the Barby gem automatically fixed this

**Comment by redfast00** [comment]
Just checked CAS-login, this seems to work.

**Comment by redfast00** [comment]
We do need the `default_url_options` and `:sendmail` delivery method (the partner mail has a link in it, and we need to know the base domain when sending the mail since the mail does not have the context of a Host header). Sendmail is the way to send mails on the server, since local SMTP does not work (yet?). @Silox probably had a reason to remove these config options though, what was it?

**Comment by Silox** [comment]
@redfast00 The upgrade replaced the files (so threw away the lines) and I was wondering if we needed them any longer on development as the mails locally seemed to work fine. I couldn't test on production if we needed those though.

**Comment by redfast00** [comment]
Alright, then I think this PR is good to merge, what do you think @mcbloch?

**Comment by mcbloch** [comment]
De `login-dev` knop werkt niet meer na het seeden. Het seeden importeert namelijk de zeus vereniging uit de dsa api en dat clasht met `Club.find_or_create_by(internal_name: 'zeus', full_name: 'Zeus WPI', display_name: 'Zeus <3')`

` Validation failed: Internal name has already been taken `

**Pull request merged**
